import { MigrationInterface, QueryRunner } from "typeorm";

/*
 * Tournament flow waves 1 and 2, on top of the Baseline (the schema of the last deploy that
 * synchronize built): explicit match slots and scores, match chat rooms, check-in, registration
 * deadline, seeding, join codes, join requests, the looking-for-team board.
 *
 * Generated by `migration:generate` against a Baseline database, then edited by hand where the
 * generated SQL would lose or strand existing rows. Every hand-written block is marked
 * "HAND-WRITTEN". Everything else is the generator's output, unchanged, so that a database
 * migrated from empty matches what synchronize builds from the current entities.
 */
export class TournamentFlowWaves1790793133773 implements MigrationInterface {
    name = 'TournamentFlowWaves1790793133773'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`
            ALTER TABLE "matches" DROP CONSTRAINT "FK_4445c1b2bd39fe81088ea640acb"
        `);
        await queryRunner.query(`
            CREATE TABLE "looking_for_team" (
                "id" SERIAL NOT NULL,
                "user_id" integer NOT NULL,
                "tournament_id" integer NOT NULL,
                "note" character varying(140),
                "created_at" TIMESTAMP NOT NULL DEFAULT now(),
                CONSTRAINT "UQ_965ac1f9f641bf4797b57964092" UNIQUE ("user_id", "tournament_id"),
                CONSTRAINT "PK_2e4fea67d2edecdcf6ed357dbcf" PRIMARY KEY ("id")
            )
        `);
        await queryRunner.query(`
            ALTER TABLE "matches"
            ADD "team1_id" integer
        `);
        await queryRunner.query(`
            ALTER TABLE "matches"
            ADD "team2_id" integer
        `);
        await queryRunner.query(`
            ALTER TABLE "matches"
            ADD "team1_score" integer
        `);
        await queryRunner.query(`
            ALTER TABLE "matches"
            ADD "team2_score" integer
        `);
        await queryRunner.query(`
            ALTER TABLE "matches"
            ADD "reported_by_team_id" integer
        `);
        await queryRunner.query(`
            ALTER TABLE "matches"
            ADD "reported_at" TIMESTAMP
        `);
        await queryRunner.query(`
            ALTER TABLE "matches"
            ADD "finished_at" TIMESTAMP
        `);
        await queryRunner.query(`
            ALTER TABLE "matches"
            ADD "group_index" integer
        `);
        await queryRunner.query(`
            ALTER TABLE "matches"
            ADD "chat_room_id" integer
        `);

        // HAND-WRITTEN: move bracket data off the old shape before match_teams goes away.
        await this.backfillMatchSlots(queryRunner);
        await this.backfillMatchColumns(queryRunner);
        // HAND-WRITTEN: the entities no longer map match_teams, so the generator leaves it
        // behind (TypeORM never drops tables it does not know). Its team FK is ON DELETE NO
        // ACTION, so keeping it would make deleting any team that ever played fail.
        await queryRunner.query(`
            DROP TABLE "match_teams"
        `);

        await queryRunner.query(`
            ALTER TABLE "tournaments"
            ADD "registration_closes_at" TIMESTAMP
        `);
        await queryRunner.query(`
            ALTER TABLE "tournaments"
            ADD "checkin_opens_at" TIMESTAMP
        `);
        await queryRunner.query(`
            ALTER TABLE "tournaments"
            ADD "finished_at" TIMESTAMP
        `);
        await queryRunner.query(`
            ALTER TABLE "tournaments"
            ADD "seed_order" jsonb
        `);
        await queryRunner.query(`
            ALTER TABLE "teams"
            ADD "checked_in_at" TIMESTAMP
        `);
        await queryRunner.query(`
            ALTER TABLE "teams"
            ADD "join_code" character varying(16)
        `);

        // HAND-WRITTEN: existing teams get a join code, as if created by the current app.
        await this.backfillJoinCodes(queryRunner);

        await queryRunner.query(`
            ALTER TABLE "teams"
            ADD CONSTRAINT "UQ_a97a53f13c97983500bd295f4b9" UNIQUE ("join_code")
        `);
        await queryRunner.query(`
            CREATE TYPE "public"."team_invitations_direction_enum" AS ENUM('INVITE', 'REQUEST')
        `);
        // Existing rows are all invitations (join requests did not exist): the INVITE default
        // is the right value for them.
        await queryRunner.query(`
            ALTER TABLE "team_invitations"
            ADD "direction" "public"."team_invitations_direction_enum" NOT NULL DEFAULT 'INVITE'
        `);
        await queryRunner.query(`
            ALTER TABLE "team_invitations"
            ADD "note" character varying(140)
        `);
        // Adding CANCELLED: the generator's rename / recreate / cast keeps every row (all old
        // labels exist in the new type) and, unlike ALTER TYPE ... ADD VALUE, is allowed in
        // the same transaction as later migrations that might use the new value.
        await queryRunner.query(`
            ALTER TYPE "public"."team_invitations_status_enum"
            RENAME TO "team_invitations_status_enum_old"
        `);
        await queryRunner.query(`
            CREATE TYPE "public"."team_invitations_status_enum" AS ENUM('PENDING', 'ACCEPTED', 'DECLINED', 'CANCELLED')
        `);
        await queryRunner.query(`
            ALTER TABLE "team_invitations"
            ALTER COLUMN "status" DROP DEFAULT
        `);
        await queryRunner.query(`
            ALTER TABLE "team_invitations"
            ALTER COLUMN "status" TYPE "public"."team_invitations_status_enum" USING "status"::"text"::"public"."team_invitations_status_enum"
        `);
        await queryRunner.query(`
            ALTER TABLE "team_invitations"
            ALTER COLUMN "status"
            SET DEFAULT 'PENDING'
        `);
        await queryRunner.query(`
            DROP TYPE "public"."team_invitations_status_enum_old"
        `);
        await queryRunner.query(`
            ALTER TABLE "matches"
            ADD CONSTRAINT "FK_4445c1b2bd39fe81088ea640acb" FOREIGN KEY ("phase_id") REFERENCES "tournament_phases"("id") ON DELETE CASCADE ON UPDATE NO ACTION
        `);
        await queryRunner.query(`
            ALTER TABLE "matches"
            ADD CONSTRAINT "FK_945b7cec59479aea39db7a001ab" FOREIGN KEY ("team1_id") REFERENCES "teams"("id") ON DELETE
            SET NULL ON UPDATE NO ACTION
        `);
        await queryRunner.query(`
            ALTER TABLE "matches"
            ADD CONSTRAINT "FK_d43f80b79f59192843534dd6350" FOREIGN KEY ("team2_id") REFERENCES "teams"("id") ON DELETE
            SET NULL ON UPDATE NO ACTION
        `);
        await queryRunner.query(`
            ALTER TABLE "matches"
            ADD CONSTRAINT "FK_411d8dc624d071367ca91c1e6e0" FOREIGN KEY ("chat_room_id") REFERENCES "chats"("id") ON DELETE
            SET NULL ON UPDATE NO ACTION
        `);
        await queryRunner.query(`
            ALTER TABLE "looking_for_team"
            ADD CONSTRAINT "FK_682c47f6126ef18724b283e17d5" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION
        `);
        await queryRunner.query(`
            ALTER TABLE "looking_for_team"
            ADD CONSTRAINT "FK_54ed045baaa1b1e15a35cb91b80" FOREIGN KEY ("tournament_id") REFERENCES "tournaments"("id") ON DELETE CASCADE ON UPDATE NO ACTION
        `);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`
            ALTER TABLE "looking_for_team" DROP CONSTRAINT "FK_54ed045baaa1b1e15a35cb91b80"
        `);
        await queryRunner.query(`
            ALTER TABLE "looking_for_team" DROP CONSTRAINT "FK_682c47f6126ef18724b283e17d5"
        `);
        await queryRunner.query(`
            ALTER TABLE "matches" DROP CONSTRAINT "FK_411d8dc624d071367ca91c1e6e0"
        `);
        await queryRunner.query(`
            ALTER TABLE "matches" DROP CONSTRAINT "FK_d43f80b79f59192843534dd6350"
        `);
        await queryRunner.query(`
            ALTER TABLE "matches" DROP CONSTRAINT "FK_945b7cec59479aea39db7a001ab"
        `);
        await queryRunner.query(`
            ALTER TABLE "matches" DROP CONSTRAINT "FK_4445c1b2bd39fe81088ea640acb"
        `);
        // HAND-WRITTEN: the old type has no CANCELLED, and the cast below would fail on it.
        // A cancelled invitation reads as a declined one to the old app.
        await queryRunner.query(`
            UPDATE "team_invitations" SET "status" = 'DECLINED' WHERE "status" = 'CANCELLED'
        `);
        await queryRunner.query(`
            CREATE TYPE "public"."team_invitations_status_enum_old" AS ENUM('PENDING', 'ACCEPTED', 'DECLINED')
        `);
        await queryRunner.query(`
            ALTER TABLE "team_invitations"
            ALTER COLUMN "status" DROP DEFAULT
        `);
        await queryRunner.query(`
            ALTER TABLE "team_invitations"
            ALTER COLUMN "status" TYPE "public"."team_invitations_status_enum_old" USING "status"::"text"::"public"."team_invitations_status_enum_old"
        `);
        await queryRunner.query(`
            ALTER TABLE "team_invitations"
            ALTER COLUMN "status"
            SET DEFAULT 'PENDING'
        `);
        await queryRunner.query(`
            DROP TYPE "public"."team_invitations_status_enum"
        `);
        await queryRunner.query(`
            ALTER TYPE "public"."team_invitations_status_enum_old"
            RENAME TO "team_invitations_status_enum"
        `);
        await queryRunner.query(`
            ALTER TABLE "team_invitations" DROP COLUMN "note"
        `);
        // HAND-WRITTEN: join requests cannot be expressed without the direction column; left
        // in place they would show up in the old app as the captain being invited to their own
        // team. They are the one thing this revert discards.
        await queryRunner.query(`
            DELETE FROM "team_invitations" WHERE "direction" = 'REQUEST'
        `);
        await queryRunner.query(`
            ALTER TABLE "team_invitations" DROP COLUMN "direction"
        `);
        await queryRunner.query(`
            DROP TYPE "public"."team_invitations_direction_enum"
        `);
        await queryRunner.query(`
            ALTER TABLE "teams" DROP CONSTRAINT "UQ_a97a53f13c97983500bd295f4b9"
        `);
        await queryRunner.query(`
            ALTER TABLE "teams" DROP COLUMN "join_code"
        `);
        await queryRunner.query(`
            ALTER TABLE "teams" DROP COLUMN "checked_in_at"
        `);
        await queryRunner.query(`
            ALTER TABLE "tournaments" DROP COLUMN "seed_order"
        `);
        await queryRunner.query(`
            ALTER TABLE "tournaments" DROP COLUMN "finished_at"
        `);
        await queryRunner.query(`
            ALTER TABLE "tournaments" DROP COLUMN "checkin_opens_at"
        `);
        await queryRunner.query(`
            ALTER TABLE "tournaments" DROP COLUMN "registration_closes_at"
        `);

        // HAND-WRITTEN: rebuild match_teams exactly as the Baseline created it, filled from
        // the slots, before the slot columns go.
        await this.restoreMatchTeams(queryRunner);

        await queryRunner.query(`
            ALTER TABLE "matches" DROP COLUMN "chat_room_id"
        `);
        await queryRunner.query(`
            ALTER TABLE "matches" DROP COLUMN "group_index"
        `);
        await queryRunner.query(`
            ALTER TABLE "matches" DROP COLUMN "finished_at"
        `);
        await queryRunner.query(`
            ALTER TABLE "matches" DROP COLUMN "reported_at"
        `);
        await queryRunner.query(`
            ALTER TABLE "matches" DROP COLUMN "reported_by_team_id"
        `);
        await queryRunner.query(`
            ALTER TABLE "matches" DROP COLUMN "team2_score"
        `);
        await queryRunner.query(`
            ALTER TABLE "matches" DROP COLUMN "team1_score"
        `);
        await queryRunner.query(`
            ALTER TABLE "matches" DROP COLUMN "team2_id"
        `);
        await queryRunner.query(`
            ALTER TABLE "matches" DROP COLUMN "team1_id"
        `);
        await queryRunner.query(`
            DROP TABLE "looking_for_team"
        `);
        await queryRunner.query(`
            ALTER TABLE "matches"
            ADD CONSTRAINT "FK_4445c1b2bd39fe81088ea640acb" FOREIGN KEY ("phase_id") REFERENCES "tournament_phases"("id") ON DELETE NO ACTION ON UPDATE NO ACTION
        `);
    }

    /**
     * HAND-WRITTEN. Fills team1_id / team2_id from the old unordered match_teams table.
     *
     * The old schema never stored which slot a team was in, so the order is reconstructed:
     *  1. A team that reached this match by winning a feeder match takes the slot that feeder
     *     names in winner_next_match_slot (the old app did record that, it just could not keep
     *     it in match_teams). This keeps started knockout brackets consistent.
     *  2. Every other team (first-round and group matches) fills the remaining slots by
     *     ascending team id: an arbitrary but deterministic order, since there is no other.
     * A match cannot hold more than two teams; if old data somehow has more, the extra rows
     * (highest team ids) are reported and not carried over.
     */
    private async backfillMatchSlots(queryRunner: QueryRunner): Promise<void> {
        const rows: { match_id: number; team_id: number; fed_slot: number | null }[] =
            await queryRunner.query(`
                SELECT mt."match_id", mt."team_id",
                       (SELECT min(f."winner_next_match_slot")
                          FROM "matches" f
                         WHERE f."winner_next_match_id" = mt."match_id"
                           AND f."winner_id" = mt."team_id"
                           AND f."winner_next_match_slot" IN (1, 2)) AS "fed_slot"
                  FROM "match_teams" mt
              ORDER BY mt."match_id", mt."team_id"
            `);

        const byMatch = new Map<number, typeof rows>();
        for (const row of rows) {
            const list = byMatch.get(row.match_id) ?? [];
            list.push(row);
            byMatch.set(row.match_id, list);
        }

        for (const [matchId, teams] of byMatch) {
            const slots: (number | null)[] = [null, null];
            const rest: number[] = [];
            for (const { team_id, fed_slot } of teams) {
                if (fed_slot != null && slots[fed_slot - 1] == null) slots[fed_slot - 1] = team_id;
                else rest.push(team_id);
            }
            for (const teamId of rest) {
                const free = slots.indexOf(null);
                if (free === -1) {
                    console.warn(`[migration] match ${matchId}: team ${teamId} dropped, both slots already filled`);
                    continue;
                }
                slots[free] = teamId;
            }
            await queryRunner.query(
                `UPDATE "matches" SET "team1_id" = $1, "team2_id" = $2 WHERE "id" = $3`,
                [slots[0], slots[1], matchId],
            );
        }
    }

    /**
     * HAND-WRITTEN. Brings matches created by the old generators up to what the current code
     * expects, without inventing anything the old rows do not say:
     *  - tournament_id / game_id: the old generators left them empty; the current code looks
     *    matches up by tournament_id. Both come from the match's phase.
     *  - group_index: the old group generator stored the group only as game_data.group ("A",
     *    "B", ...); the current code reads group_index (0 for A).
     *  - READY: the old app created every match WAITING, even with both teams known. Now
     *    WAITING means "a slot is still empty" and only READY matches can be reported.
     */
    private async backfillMatchColumns(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`
            UPDATE "matches" m
               SET "tournament_id" = COALESCE(m."tournament_id", p."tournament_id"),
                   "game_id" = COALESCE(m."game_id", p."game_id")
              FROM "tournament_phases" p
             WHERE p."id" = m."phase_id"
               AND (m."tournament_id" IS NULL OR m."game_id" IS NULL)
        `);
        await queryRunner.query(`
            UPDATE "matches"
               SET "group_index" = ascii("game_data"->>'group') - ascii('A')
             WHERE "group_index" IS NULL
               AND "game_data"->>'group' ~ '^[A-Z]$'
        `);
        await queryRunner.query(`
            UPDATE "matches"
               SET "status" = 'READY'
             WHERE "status" = 'WAITING'
               AND "team1_id" IS NOT NULL
               AND "team2_id" IS NOT NULL
        `);
    }

    /**
     * HAND-WRITTEN. Gives every existing team a join code in the app's format (see
     * src/modules/teams/utils/join-code.ts): 10 characters from the same 57-character
     * alphabet, each picked by a random byte modulo 57. The bytes come from gen_random_uuid()
     * (built in since Postgres 13, cryptographically strong), using only its fully random
     * bytes: 6 and 8 carry the version and variant bits. The UNIQUE constraint is added right
     * after; a collision (odds ~1 in 10^17 per pair) would abort the migration, not corrupt it.
     */
    private async backfillJoinCodes(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`
            UPDATE "teams" t
               SET "join_code" = c."code"
              FROM (
                    SELECT s."id",
                           (SELECT string_agg(
                                       substr('ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789',
                                              1 + get_byte(s."bytes", i) % 57, 1),
                                       '' ORDER BY ord)
                              FROM unnest(ARRAY[0, 1, 2, 3, 4, 5, 9, 10, 11, 12]) WITH ORDINALITY AS u(i, ord)
                           ) AS "code"
                      FROM (SELECT "id", decode(replace(gen_random_uuid()::text, '-', ''), 'hex') AS "bytes"
                              FROM "teams") s
                   ) c
             WHERE c."id" = t."id"
               AND t."join_code" IS NULL
        `);
    }

    /** HAND-WRITTEN. Inverse of the match_teams drop: same DDL as the Baseline, then refill. */
    private async restoreMatchTeams(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`
            CREATE TABLE "match_teams" (
                "match_id" integer NOT NULL,
                "team_id" integer NOT NULL,
                CONSTRAINT "PK_03542102c151718b118f6132b22" PRIMARY KEY ("match_id", "team_id")
            )
        `);
        await queryRunner.query(`
            CREATE INDEX "IDX_98e38a7c7139bbda0c4f2fcb59" ON "match_teams" ("match_id")
        `);
        await queryRunner.query(`
            CREATE INDEX "IDX_b4806f0183effb3d190eef583f" ON "match_teams" ("team_id")
        `);
        await queryRunner.query(`
            ALTER TABLE "match_teams"
            ADD CONSTRAINT "FK_98e38a7c7139bbda0c4f2fcb594" FOREIGN KEY ("match_id") REFERENCES "matches"("id") ON DELETE CASCADE ON UPDATE CASCADE
        `);
        await queryRunner.query(`
            ALTER TABLE "match_teams"
            ADD CONSTRAINT "FK_b4806f0183effb3d190eef583f1" FOREIGN KEY ("team_id") REFERENCES "teams"("id") ON DELETE NO ACTION ON UPDATE NO ACTION
        `);
        await queryRunner.query(`
            INSERT INTO "match_teams" ("match_id", "team_id")
            SELECT "id", "team1_id" FROM "matches" WHERE "team1_id" IS NOT NULL
             UNION
            SELECT "id", "team2_id" FROM "matches" WHERE "team2_id" IS NOT NULL
        `);
    }
}
