// Team flows, LFT, registration deadline, check-in.
const L = require('./lib');
const { api, must, check } = L;
function userLeaks(obj, path = '$', out = []) {
  if (Array.isArray(obj)) obj.forEach((x, i) => userLeaks(x, `${path}[${i}]`, out));
  else if (obj && typeof obj === 'object') {
    if ('username' in obj) for (const k of ['mail', 'role', 'banUntil', 'twoFactorEnabled', 'isEmailVerified', 'passwordHash', 'firstName', 'lastName']) if (k in obj) out.push(`${path}.${k}`);
    for (const [k, v] of Object.entries(obj)) userLeaks(v, `${path}.${k}`, out);
  }
  return out;
}
const myInvites = async (u) => must(api(u, 'GET', '/teams/invitations/my'), 'my invites');

(async () => {
  const admin = await L.makeAdmin(await L.newUser('admin'));
  const g = await L.game(admin, 2); // team size 2
  const tour = await L.tournament(admin, g.id, { max: 2 });
  const [cap, u1, u2, u3, u4, u5] = await Promise.all([1, 2, 3, 4, 5, 6].map(() => L.newUser('p')));

  console.log('# create / one team per user');
  let r = await api(cap, 'POST', '/teams', { name: 'Alpha', tournament_id: tour.id });
  check(r.status === 201, 'create team', r.body);
  const team = r.body;
  check(!('join_code' in team) || !team.join_code || true, 'create response');
  r = await api(cap, 'POST', '/teams', { name: 'Alpha2', tournament_id: tour.id });
  check(r.status === 400 || r.status === 409, 'second team in same tournament refused', r.status);
  r = await api(u5, 'POST', '/teams', { name: 'Alpha', tournament_id: tour.id });
  console.log('   duplicate team name in tournament ->', r.status, JSON.stringify(r.body).slice(0, 100));
  const dupTeam = r.status === 201 ? r.body : null;
  if (dupTeam) await must(api(u5, 'DELETE', `/teams/${dupTeam.id}`), 'del dup');

  console.log('# invite / decline / cancel / accept');
  r = await api(cap, 'PATCH', `/teams/${team.id}/invite`, { userId: u1.id });
  check(r.status === 200, 'invite u1', r.body);
  check(userLeaks(r.body).length === 0, 'invite response leaks nothing', userLeaks(r.body));
  const inv1 = r.body;
  r = await api(u2, 'PATCH', `/teams/${team.id}/invite`, { userId: u3.id });
  check(r.status === 403, 'non-member cannot invite', r.status);
  r = await api(cap, 'PATCH', `/teams/${team.id}/invite`, { userId: u1.id });
  check(r.status >= 400, 'duplicate invite refused', r.status);
  let mi = await myInvites(u1);
  check(mi.some(i => i.id === inv1.id), 'u1 sees invitation', mi);
  check(userLeaks(mi).length === 0, 'my invitations leak nothing', userLeaks(mi));
  r = await api(u2, 'PATCH', `/teams/invitations/${inv1.id}/accept`);
  check(r.status === 403 || r.status === 404 || r.status === 400, 'someone else cannot accept u1 invite', r.status);
  r = await api(cap, 'DELETE', `/teams/invitations/${inv1.id}`);
  check(r.status === 200, 'captain cancels invite', r.body);
  r = await api(u1, 'PATCH', `/teams/invitations/${inv1.id}/accept`);
  check(r.status >= 400, 'cancelled invite cannot be accepted', r.status);
  r = await api(cap, 'PATCH', `/teams/${team.id}/invite`, { userId: u1.id });
  const inv1b = r.body;
  r = await api(u1, 'PATCH', `/teams/invitations/${inv1b.id}/decline`);
  check(r.status === 200, 'u1 declines');
  r = await api(cap, 'PATCH', `/teams/${team.id}/invite`, { userId: u1.id });
  check(r.status === 200, 're-invite after decline', r.status);
  r = await api(u1, 'PATCH', `/teams/invitations/${r.body.id}/accept`);
  check(r.status === 200, 'u1 accepts', r.body);
  let mine = await must(api(u1, 'GET', `/teams/mine?tournament_id=${tour.id}`));
  check(mine.team && mine.team.id === team.id && mine.team.members.length === 2, 'u1 is in the team', mine.team);
  check(userLeaks(mine).length === 0, '/teams/mine leaks nothing', userLeaks(mine));

  console.log('# join code + join request');
  r = await api(u2, 'GET', `/teams/${team.id}/join-code`);
  check(r.status === 403, 'non-member cannot read join code', r.status);
  const code = (await must(api(u1, 'GET', `/teams/${team.id}/join-code`))).joinCode;
  check(/^[A-Za-z0-9]{6,}$/.test(code), 'join code format', code);
  r = await api(u1, 'PATCH', `/teams/${team.id}/join-code/regenerate`);
  check(r.status === 403, 'plain member cannot regenerate code', r.status);
  r = await api(cap, 'PATCH', `/teams/${team.id}/join-code/regenerate`);
  check(r.status === 200 && r.body.joinCode !== code, 'captain regenerates', r.body);
  const code2 = r.body.joinCode;
  r = await api(u2, 'POST', '/teams/join', { code });
  check(r.status >= 400, 'old code no longer works', r.status);
  r = await api(u2, 'POST', '/teams/join', { code: code2 });
  check(r.status === 200 || r.status === 201, 'u2 joins by code (bench slot)', r.status + ' ' + JSON.stringify(r.body));
  mine = await must(api(cap, 'GET', `/teams/mine?tournament_id=${tour.id}`));
  console.log('   roster size now', mine.team.members.length, 'spots left', mine.teamSpotsLeft);
  r = await api(u3, 'POST', `/teams/${team.id}/requests`, { note: 'pls' });
  console.log('   join request when roster', mine.teamSpotsLeft === 0 ? 'full' : 'open', '->', r.status, JSON.stringify(r.body).slice(0, 120));

  console.log('# rename / transfer / admin / leave');
  r = await api(u1, 'PATCH', `/teams/${team.id}/rename`, { name: 'Hacked' });
  check(r.status === 403, 'plain member cannot rename', r.status);
  r = await api(cap, 'PATCH', `/teams/${team.id}/rename`, { name: 'Bravo' });
  check(r.status === 200 && r.body.name === 'Bravo', 'captain renames', r.body);
  r = await api(cap, 'PATCH', `/teams/${team.id}/promote`, { userId: u2.id });
  check(r.status === 200, 'promote u2 to admin');
  r = await api(u2, 'PATCH', `/teams/${team.id}/transfer-captain`, { userId: u1.id });
  check(r.status === 403, 'admin (non-captain) cannot transfer captaincy', r.status);
  r = await api(cap, 'PATCH', `/teams/${team.id}/transfer-captain`, { userId: u3.id });
  check(r.status >= 400, 'cannot transfer to non-member', r.status);
  r = await api(cap, 'PATCH', `/teams/${team.id}/transfer-captain`, { userId: u1.id });
  check(r.status === 200 && r.body.captain_id === u1.id, 'captain transfers to u1', r.body);
  check(userLeaks(r.body).length === 0, 'transfer response leaks nothing', userLeaks(r.body));
  r = await api(cap, 'PATCH', `/teams/${team.id}/rename`, { name: 'Charlie' });
  check(r.status === 200, 'old captain is now admin and may rename', r.status);
  // u2 (admin) leaves -> loses admin rights
  r = await api(u2, 'PATCH', `/teams/${team.id}/leave`);
  check(r.status === 200, 'admin u2 leaves', r.body);
  r = await api(u2, 'PATCH', `/teams/${team.id}/invite`, { userId: u4.id });
  check(r.status === 403, 'ex-member admin cannot invite', r.status);
  r = await api(u2, 'PATCH', `/teams/${team.id}/kick`, { userId: cap.id });
  check(r.status === 403, 'ex-member admin cannot kick', r.status);
  r = await api(u2, 'PATCH', `/teams/${team.id}/lock`);
  check(r.status === 403, 'ex-member admin cannot lock', r.status);
  r = await api(u2, 'PATCH', `/teams/${team.id}/rename`, { name: 'Exmember' });
  check(r.status === 403, 'ex-member admin cannot rename', r.status);
  r = await api(u2, 'POST', '/teams/join', { code: code2 });
  check(r.status === 200 || r.status === 201, 'u2 re-joins by code', r.status);
  r = await api(u2, 'PATCH', `/teams/${team.id}/rename`, { name: 'Exmember' });
  check(r.status === 403, 're-joined ex-admin has no admin rights left', r.status);
  r = await api(u1, 'PATCH', `/teams/${team.id}/kick`, { userId: u2.id });
  check(r.status === 200, 'captain kicks u2', r.status);

  console.log('# lock / unlock / LFT');
  r = await api(u4, 'POST', `/teams/lft/${tour.id}`, { note: 'support main' });
  check(r.status === 201 || r.status === 200, 'u4 flags LFT', r.body);
  let lft = await must(api(u5, 'GET', `/teams/lft/${tour.id}`));
  check(lft.some(e => (e.user && e.user.id === u4.id) || e.user_id === u4.id), 'u4 on the LFT board', lft);
  check(userLeaks(lft).length === 0, 'LFT board leaks nothing', userLeaks(lft));
  r = await api(u1, 'PATCH', `/teams/${team.id}/lock`);
  check(r.status === 200 && r.body.status === 'LOCKED', 'captain locks', r.body);
  r = await api(cap, 'PATCH', `/teams/${team.id}/invite`, { userId: u4.id });
  check(r.status >= 400, 'locked team cannot invite', r.status);
  r = await api(u4, 'POST', '/teams/join', { code: code2 });
  check(r.status >= 400, 'locked team cannot be joined by code', r.status);
  r = await api(u1, 'PATCH', `/teams/${team.id}/unlock`);
  check(r.status === 200 && r.body.status === 'DRAFT', 'captain unlocks', r.body);
  r = await api(cap, 'PATCH', `/teams/${team.id}/invite`, { userId: u4.id });
  check(r.status === 200, 'invite u4 after unlock');
  r = await api(u4, 'PATCH', `/teams/invitations/${r.body.id}/accept`);
  check(r.status === 200, 'u4 accepts');
  lft = await must(api(u5, 'GET', `/teams/lft/${tour.id}`));
  check(!lft.some(e => (e.user && e.user.id === u4.id) || e.user_id === u4.id), 'u4 off the LFT board after joining', lft);

  console.log('# accept invite pulls you out of other DRAFT team, never out of LOCKED');
  const t2cap = u5;
  const t2 = await must(api(t2cap, 'POST', '/teams', { name: 'Delta', tournament_id: tour.id }), 'team2');
  const inv = await must(api(t2cap, 'PATCH', `/teams/${t2.id}/invite`, { userId: u4.id }));
  await must(api(u1, 'PATCH', `/teams/${team.id}/lock`), 'lock again');
  r = await api(u4, 'PATCH', `/teams/invitations/${inv.id}/accept`);
  check(r.status >= 400, 'member of a LOCKED team cannot accept another invite', r.status + ' ' + JSON.stringify(r.body));
  mine = await must(api(u4, 'GET', `/teams/mine?tournament_id=${tour.id}`));
  check(mine.team && mine.team.id === team.id, 'u4 still in locked team');

  console.log('# max_participants');
  const t2cap2 = await L.newUser('p');
  // tournament max is 2. Team 1 LOCKED. Team2 locks -> 2. third team cannot lock
  const memb = await L.newUser('p');
  const c2 = (await must(api(t2cap, 'GET', `/teams/${t2.id}/join-code`))).joinCode;
  await must(api(memb, 'POST', '/teams/join', { code: c2 }), 'join t2');
  await must(api(t2cap, 'PATCH', `/teams/${t2.id}/lock`), 'lock t2');
  const t3 = await must(api(t2cap2, 'POST', '/teams', { name: 'Echo', tournament_id: tour.id }), 'team3');
  const m3 = await L.newUser('p');
  const c3 = (await must(api(t2cap2, 'GET', `/teams/${t3.id}/join-code`))).joinCode;
  await must(api(m3, 'POST', '/teams/join', { code: c3 }), 'join t3');
  r = await api(t2cap2, 'PATCH', `/teams/${t3.id}/lock`);
  check(r.status >= 400, 'third team cannot lock (max 2)', r.status + ' ' + JSON.stringify(r.body));
  const av = await must(api(m3, 'GET', `/teams/tournament/${tour.id}/availability`));
  console.log('   availability:', JSON.stringify(av));

  console.log('# registration deadline');
  const past = new Date(Date.now() - 60000).toISOString();
  const future = new Date(Date.now() + 3600000).toISOString();
  const td = await L.tournament(admin, g.id, { extra: { registration_closes_at: past } });
  r = await api(u3, 'POST', '/teams', { name: 'Late', tournament_id: td.id });
  check(r.status === 400, 'team creation after deadline refused', r.status);
  r = await api(admin, 'PATCH', `/tournaments/${td.id}`, { registration_closes_at: future, scheduled_at: new Date(Date.now() + 1800000).toISOString() });
  check(r.status === 400, 'deadline after scheduled_at refused', r.status);
  r = await api(admin, 'PATCH', `/tournaments/${td.id}`, { registration_closes_at: future });
  check(r.status === 200, 'admin extends deadline', r.body);
  r = await api(u3, 'POST', '/teams', { name: 'Late', tournament_id: td.id });
  check(r.status === 201, 'team creation before deadline ok', r.status);
  const late = r.body;
  await must(api(admin, 'PATCH', `/tournaments/${td.id}`, { registration_closes_at: past }), 'close');
  r = await api(u3, 'PATCH', `/teams/${late.id}/invite`, { userId: u5.id });
  console.log('   invite after deadline ->', r.status);
  if (r.status === 200) { const a = await api(u5, 'PATCH', `/teams/invitations/${r.body.id}/accept`); check(a.status === 400, 'accepting an invite after the deadline refused', a.status + ' ' + JSON.stringify(a.body)); }
  const lc = (await must(api(u3, 'GET', `/teams/${late.id}/join-code`))).joinCode;
  r = await api(u2, 'POST', '/teams/join', { code: lc });
  check(r.status === 400, 'join by code after deadline refused', r.status);

  console.log('# check-in');
  const tc = await L.tournament(admin, g.id, { extra: { checkin_opens_at: future } });
  const ents = await L.teams(tc.id, 3, 2);
  r = await api(ents[0].captain, 'POST', `/teams/${ents[0].team.id}/check-in`);
  check(r.status === 400, 'check-in before window refused', r.status);
  let ci = await must(api(admin, 'GET', `/tournaments/${tc.id}/checkin`));
  check(ci.state === 'upcoming' && !ci.required, 'checkin upcoming, not required', ci);
  await must(api(admin, 'PATCH', `/tournaments/${tc.id}`, { checkin_opens_at: past }), 'open checkin');
  ci = await must(api(admin, 'GET', `/tournaments/${tc.id}/checkin`));
  check(ci.state === 'open' && ci.required && ci.willBeArchived.length === 3, 'open, all 3 would be archived', ci);
  r = await api(ents[0].members[1], 'POST', `/teams/${ents[0].team.id}/check-in`);
  check(r.status === 403, 'plain member cannot check in', r.status);
  r = await api(ents[0].captain, 'POST', `/teams/${ents[0].team.id}/check-in`);
  check(r.status === 201 && r.body.checked_in_at, 'captain checks in', r.body);
  check(userLeaks(r.body).length === 0, 'check-in response leaks nothing', userLeaks(r.body));
  r = await api(admin, 'POST', `/teams/${ents[1].team.id}/check-in`);
  check(r.status === 201, 'global admin checks a team in', r.status);
  const seed = await must(api(admin, 'GET', `/tournaments/${tc.id}/seeding`));
  check(seed.teams.length === 2 && seed.excluded.some(e => e.id === ents[2].team.id && e.reason === 'not_checked_in'), 'seeding drops the absent team', seed);
  r = await api(ents[2].captain, 'PATCH', `/teams/${ents[2].team.id}/unlock`);
  console.log('   unlock during check-in ->', r.status);
  await must(api(admin, 'POST', `/tournaments/${tc.id}/start`), 'start checkin tournament');
  const tcd = await must(api(admin, 'GET', `/tournaments/${tc.id}`));
  const st = Object.fromEntries(tcd.teams.map(t => [t.id, t.status]));
  check(st[ents[2].team.id] === 'ARCHIVED', 'not-checked-in team archived', st);
  check(tcd.seed_order.length === 2, 'two entrants');
  r = await api(ents[2].captain, 'POST', `/teams/${ents[2].team.id}/check-in`);
  check(r.status === 400, 'check-in after start refused', r.status);
  r = await api(ents[0].captain, 'PATCH', `/teams/${ents[0].team.id}/leave`);
  console.log('   leave a team in a running tournament ->', r.status, JSON.stringify(r.body).slice(0, 120));
  r = await api(ents[0].members[1], 'PATCH', `/teams/${ents[0].team.id}/leave`);
  check(r.status === 403, 'member cannot leave a team in a running tournament', r.status);
  r = await api(ents[0].captain, 'DELETE', `/teams/${ents[0].team.id}`);
  check(r.status >= 400, 'cannot delete a team in a running tournament', r.status + ' ' + JSON.stringify(r.body));
  r = await api(ents[0].captain, 'PATCH', `/teams/${ents[0].team.id}/rename`, { name: 'Zulu' });
  check(r.status >= 400, 'cannot rename after start', r.status);
  r = await api(ents[0].captain, 'PATCH', `/teams/${ents[0].team.id}/kick`, { userId: ents[0].members[1].id });
  check(r.status >= 400, 'cannot kick after start', r.status + ' ' + JSON.stringify(r.body));
  process.exit(L.summary() ? 1 : 0);
})().catch(e => { console.error('CRASH', e); process.exit(2); });
